# Generated by Django 3.2.10 on 2022-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_alter_request_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("RQ", "Request"),
                    ("PS", "Partially Settled"),
                    ("CL", "Closed"),
                    ("DL", "Deleted"),
                ],
                default="RQ",
                max_length=16,
            ),
        ),
    ]
