# Generated by Django 3.2.10 on 2022-10-13 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request", "0004_auto_20220929_1357"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllist",
            name="called_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="called_to_all",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calllist",
            name="called_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="called_by_all",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
