# Generated by Django 3.2.10 on 2023-06-27 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20221013_1107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calllist',
            unique_together=set(),
        ),
    ]
