# Generated by Django 3.2.10 on 2023-06-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_alter_calllist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllist',
            name='called_to',
        ),
    ]
