# Generated by Django 3.2.10 on 2022-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Soumya', max_length=256),
            preserve_default=False,
        ),
    ]
