# Generated by Django 3.2.10 on 2023-06-27 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 5, 29, 10, 105561, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
