# Generated by Django 3.2.10 on 2023-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_otp_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
